import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { InfoTab } from '@impulsogov/design-system';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <InfoTab
          contentList={[
            {
              buttonLink: '/',
              buttonTitle: 'SOBRE SAÚDE MENTAL',
              leftTitle: 'Saúde Mental',
              rightContent: 'Uma plataforma gratuita, que utiliza bases de dados públicas para auxiliar na gestão dos serviços de saúde mental do município. Conheça mais sobre o trabalho realizado pela Impulso em parceria com o Instituto Cactus e o município de Aracaju (SE).',
              rightTitle: 'O que é a plataforma de indicadores de Saúde Mental?'
            },
            {
              buttonLink: '/2',
              buttonTitle: 'entenda',
              leftTitle: 'Glossário',
              rightContent: 'Acesse um siglário e a ficha técnica de nossos indicadores para compreender como eles são calculados, quais são as bases de dados que os alimentam, com qual periodicidade eles são atualizados e muito mais',
              rightTitle: 'Entenda como interpretar os indicadores'
            }
          ]}
        />

      </main>
    </>
  )
}
